version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - docker-compose up -d
      - |
        until curl -s http://localhost:4444/status | grep '"ready":true'; do
          echo "Waiting for Selenium Grid..."
          sleep 5
        done

  build:
    commands:
      - mvn clean test

  post_build:
    commands:
      - docker-compose down