version: 0.2

phases:
  install:
    commands:
      - echo Installing docker-compose
      - curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - echo Installing jq
      - yum install -y jq

  pre_build:
    commands:
      - echo Starting Selenium Grid
      - docker-compose up -d
      - |
        timeout 180 bash -c '
        until curl -s http://localhost:4444/status | jq -r '.value.ready' | grep -q true; do
          echo "Grid not ready yet..."
          sleep 5
        done
        '
  build:
    commands:
      - mvn test

  post_build:
    commands:
      - docker-compose down